### ISSUE TITLE
what is admin panel password and username ?

### ISSUE THREAD

**Issue by azzipskcin** [Philipinho/Simple-PHP-Blog#11]

**Comment by Philipinho** [comment]
There is no default admin user.
Manually create an admin user via SQL.
Password hash should be in `bcrypt`.

**Comment by zeldaus** [comment]
okey i will try and tell you 


thank you !

**Comment by Philipinho** [comment]
I just made some updates to the code.

**Default admin info**
Username: admin
Password: 12345

**Comment by azzipskcin** [comment]
thank yu
