### ISSUE TITLE
How to make url google friendly ?

### ISSUE THREAD

**Issue by PManuel1986** [Philipinho/Simple-PHP-Blog#15]
e.g. blog/article name 
or  /2021/11/05/projekt-dashboard/

**Comment by Philipinho** [comment]
You achieve that with .htaccess rewrite rules.

**Comment by PManuel1986** [comment]
what do i need there .htaccess rewrite rules. specify this is what my .htaccess looks like right now
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^/betasendeplan/
RewriteCond %{HTTP_HOST} ^(www.)?radio-schlauti.de$
RewriteRule ^(.*)$ /index.php?path=$1 [NC,L,QSA]
RewriteCond %{HTTP_USER_AGENT} ^facebookexternalhit/1\.1

**Comment by Philipinho** [comment]
Allow me a few days and I will make an official implementation.

**Comment by Philipinho** [comment]
Please install and test the URL rewrite branch.
I would love to hear your feedback.
https://github.com/Philipinho/Simple-PHP-Blog/tree/url-rewrite

**Comment by PManuel1986** [comment]
thank you thank you for the good support it works
