### ISSUE TITLE
Parse error: syntax error, unexpected '$dbcon' (T_VARIABLE) in /var/www/html/connect.php on line 8

### ISSUE THREAD

**Issue by MJB-Khorasani** [Philipinho/Simple-PHP-Blog#8]
Hi, when I clone your code and run it. why does this happen?
![Screenshot_2020-09-27_14-22-07](https://user-images.githubusercontent.com/46071328/94363173-4a503c00-00cd-11eb-9550-ab1c79310f78.png)
what is that mean? something related to database?

**Comment by Philipinho** [comment]
Hi, I just fixed this https://github.com/Philipinho/Simple-PHP-Blog/commit/7407354e8f82312c608c3a10d76aa005c42cbbb3
